# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install: cd ReactiveHealthKit\ Tests && pod install && cd -
script:
- xctool test -workspace ReactiveHealthKit\ Tests/ReactiveHealthKit.xcworkspace -scheme ReactiveHealthKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
